[build]
  base = "."
  publish = "public/"
  command = "yarn && gatsby build"
#  functions = "project/functions/" // TODO: LAMBDA FUNCTIONS

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = false
    minify = false
  [build.processing.js]
    bundle = false
    minify = false
  [build.processing.html]
    pretty_urls = false
  [build.processing.images]
    compress = false

#[[plugins]]
 # package = "netlify-plugin-gatsby-cache"

 [headers]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[build.analyze]
  command = "ANALYZE=true gatsby build"

#[[headers]]
#  for = "/*" # This defines which paths this specific [[headers]] block will cover.
#  [headers.values]
#    X-Frame-Options = "DENY"
#    X-XSS-Protection = "1; mode=block"
#    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
#    # Multi-key header rules are expressed with multi-line strings
#    Link = '''
#    </assets/css/base.css>; rel=preload; as=style, \
#    </assets/css/base2.css>; rel=preload; as=style, \
#    </assets/css/base3.css>; rel=preload; as=style'''
#    # Basic-Auth allows you to password protect your whole site but is only available
#    # to paid accounts
#    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"
